import = ["~/.config/alacritty/gruvbox_dark.toml"]

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 20.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "None"

[window.padding]
x = 8
y = 8
