#!/usr/bin/env zsh

for config_file ("$XDG_CONFIG_HOME"/zsh/.zshrc.d/*); do
	source "$config_file"
done
unset config_file

# colorize (BSD) ls output
export CLICOLOR=1

# Allow comments even in interactive shells
setopt INTERACTIVE_COMMENTS
# Print option settings in a combined list marked `on' if in non-default state, else `off'
setopt KSH_OPTION_PRINT
# Disallow append redirection (>>) on a file that does not already exist
# Use `>>!' or `>>|' to create and append a file
setopt NO_APPEND_CREATE
# Disallow `>' redirection to truncate an existing file
# Use `>!' or `>|' to truncate a file
setopt NO_CLOBBER

# Enable vi keys in menuselect
zmodload zsh/complist
bindkey -M menuselect '^h' vi-backward-char
bindkey -M menuselect '^k' vi-up-line-or-history
bindkey -M menuselect '^l' vi-forward-char
bindkey -M menuselect '^j' vi-down-line-or-history
bindkey -M menuselect '^xg' clear-screen
bindkey -M menuselect '^xi' vi-insert
bindkey -M menuselect '^xh' accept-and-hold
bindkey -M menuselect '^xn' accept-and-infer-next-history
bindkey -M menuselect '^xu' undo

# NOTE: zsh-syntax-highlighting has to be sourced before zsh-history-substring-search
source "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

source "$HOMEBREW_PREFIX/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

source "$HOMEBREW_PREFIX/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh"

# NOTE: zoxide init has to be evaluated after compinit
autoload -Uz compinit
compinit -d "$XDG_CACHE_HOME/zsh/zcompcache/.zcompdump"

eval "$(zoxide init --cmd j zsh)"

type -p starship &>/dev/null && eval "$(starship init zsh)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
