---
- name: Install tmux terminal multiplexer and tpm
  community.general.homebrew:
    name:
      - tmux
      - tpm
    state: latest

- name: Run tpm script `install_plugins.sh` on arm64
  ansible.builtin.command: /opt/homebrew/share/tpm/scripts/install_plugins.sh
  when: ansible_architecture == "arm64"

- name: Run tpm script `install_plugins.sh` on x86_64
  ansible.builtin.command: /usr/local/share/tpm/scripts/install_plugins.sh
  when: ansible_architecture == "x86_64"
